
name: release

on:  
  push:    
    branches:      
      - main

jobs:  
  release-diffusechain-pypi:    
    runs-on: ubuntu-20.04    
    steps:      
      - name: Checkout repository        
        uses: actions/checkout@v2      
      - name: Setup python 3.11        
        uses: actions/setup-python@v2        
        with:          
          python-version: 3.11      
      - name: Publish to pypi        
        uses: ./        
        with:          
          project-name: diffusechain
          pypi-token: ${{ secrets.PYPI_ACTION_TOKEN }}          
          pyproject-folder: ./
